### ISSUE TITLE
大佬，开放指定端口的nat小鸡如何使用呢。

### ISSUE THREAD

**Issue by yuyscll7** [fscarmen/sba#1]
我尝试修改了sba下的nginx.conf tunnel.tml 以及sing-box-conf内的inboud的相应端口，并将cf的tunnel 进行更改。但是好像没生效

**Comment by fscarmen** [comment]
那些nat鸡，IP几乎都是被封的，用不了直连端口了，直接用Argo，那个不需要设置端口，保持就行了。
