### ISSUE TITLE
How to auto setup and start SB-A?

### ISSUE THREAD

**Issue by ancientcatz** [fscarmen/sba#12]
I tried using parameters for setup but only argo can be run. Is there a way to setup it automatically? Because I plan to create a docker image for SB-A.

**Comment by fscarmen** [comment]
https://github.com/fscarmen/sing-box/blob/main/README.md#6docker-%E5%92%8C-docker-compose-%E5%AE%89%E8%A3%85

here is the sing-box docker with argo.

**Comment by ancientcatz** [comment]
> https://github.com/fscarmen/sing-box/blob/main/README.md#6docker-%E5%92%8C-docker-compose-%E5%AE%89%E8%A3%85
> 
> here is the sing-box docker with argo.

Thank you, this is very helpful. But unfortunately this one can't custom path. Maybe I need to make my own image.

**Comment by fscarmen** [comment]
I don't understand until now what you need?

**Comment by ancientcatz** [comment]
> I don't understand until now what you need?

This is the default path
`vless://a0f22e5c-f5ce-11ee-8c02-4bf1fd4489e2@time.cloudflare.com:80?type=ws&encryption=none&host=domain.com&path=%2F2a0f22e5c-f5ce-11ee-8c02-4bf1fd4489e2-vless%3Fed%3D2048#gcp-vless-ws-ntls`
I want something like this
`vless://a0f22e5c-f5ce-11ee-8c02-4bf1fd4489e2@time.cloudflare.com:80/?type=ws&encryption=none&host=domain.com&path=%2Fws-vl%3Fed%3D2048#gcp-vless-ws-ntls`

**Comment by ancientcatz** [comment]
Actually, this issue has been resolved. So I'll just close it now.
