### ISSUE TITLE
增添hysteria2和tuic协议出错

### ISSUE THREAD

**Issue by clift190** [fscarmen/sba#13]
argo隧道安置成功后， 选择8安装 Sing-box 协议全家桶脚本，再选择6 增加/删除协议 (sb -r) ，增添hysteria2和tuic协议出错，如下图：
![sba](https://github.com/fscarmen/sba/assets/71013126/85fdac15-6fef-4f43-ae50-d6fd5201292d)

**Comment by fscarmen** [comment]
估计你是乱用脚本了，本脚本没有hy2和 tuic的

**Comment by clift190** [comment]
已更新操作说明。另外：
1、使用sba脚本成功后，再使用sing-box脚本，提示冲突
2、使用argox脚本安装argo隧道成功后，再用sing-box脚本能成功安装hy2和tuic

我其实想要的就是：用singbox核心安装hy2、tuic，以及套上argo隧道的vless

**Comment by fscarmen** [comment]
用Sing-box的docker版本，那个支持 argo
