### ISSUE TITLE
大佬，关于导出Shadowrocket不可用的情况。

### ISSUE THREAD

**Issue by cheat0916** [fscarmen/sba#2]
大佬，我是Pz，学着用Issues了，哈哈哈。
还是之前跟你过的那种情况：
成功生成节点后，V2rayN的正常使用。
Shadowrocket的导入Shadowrocket后，可以测出延时，但是无法使用。
将V2rayN的导入Shadowrocket后可用。
辛苦啦1

**Comment by fscarmen** [comment]
你pm一下节点信息给我看看

**Comment by cheat0916** [comment]
> hpm一下节点信息给我看看

好的，已发，辛苦啦
