### ISSUE TITLE
老大辛苦了，提个意见，这个脚本考虑跟sing-box 那个合并吗？

### ISSUE THREAD

**Issue by sw19999** [fscarmen/sba#4]
老大的这个脚本跟sing-box两个脚本合并了其实也可以啊，这样又可以用argo 的vless和vmess中转（有域名挂载CF非常方便）临时argo通道老是变化不方便。

又可以用Reality直连，再加上可选开启hysteria2或者tuic v5（不是可选也可以）这样又方便快捷，不用装2个。常用协议都齐全了。

大佬考虑一下，谢谢

**Comment by fscarmen** [comment]
使用的场景有不同的，sba是为了nat小鸡，没有充足的对外监听端口设计的。会比sing-box全家桶多了`nginx`和`cloudflared`要安装的。而sing-box全家桶适合所有端口都开放的机器，要使用cdn也不用Argo，直接把 WSS 的那两个协议的端口改为 443 （上几天改为从100开始了）即可

**Comment by sw19999** [comment]
感谢老大回复，在cf设置 端口回源以使用 cdn，vmess ws可以了。其它协议直连。sing-box那个脚本一般够用了。
