### ISSUE TITLE
机器重启后，singbox服务需要手动重启下，节点才可使用

### ISSUE THREAD

**Issue by nbeeeeeeeeee** [fscarmen/sba#5]
重启后，节点无法连接，打开脚本后argo与singbox显示开启状态，argo域名正常，通过脚本手动关闭 启动 singbox服务，节点可以连接

机器：甲骨文arm  
系统：ubuntu 20.04
bbr算法：bbr fq_pie

脚本信息：

 脚本版本:1.0.3
 功能新增:1. 支持 Sing-box 1.8.0 最新的 Rule Set 和 Experimental; 2. api.openai.com 分流到 WARP IPv4，其他 openai 网站分流到 WARP IPv6; 3. 更换一些优选域名
 系统信息:
         当前操作系统:Ubuntu 20.04.6 LTS
         内核:6.6.9
         处理器架构:
         虚拟化:kvm 
         IPv4: 138.2.*.*  美国  Oracle Corporation 
         IPv6:      
         Argo: 开启      Version: 2023.10.0      内存占用: 47.5 MB       
         Sing-box: 开启  Version: 1.8.0-beta.9           内存占用: 34.0 MB

**Comment by fscarmen2** [comment]
我要试下才行，我极少重启机器的

**Comment by fscarmen** [comment]
我要试下才行，我极少重启机器的。

**Comment by fscarmen** [comment]
谢谢，已经复现bug了，nginx漏了处理，我会处理安装脚本，你可以通过以下指令升级
```
sb -a; sed -i '/ExecStart/s/.*/ExecStartPre=nginx -c \/etc\/sba\/nginx.conf\n&/' /etc/systemd/system/argo.service; sb -a; sb -n
```

**Comment by nbeeeeeeeeee** [comment]
感谢大佬，脚本很好用哦

**Comment by fscarmen** [comment]
我觉得这个比 argo + xray 好的，多路复用好像挺不错的。
