### ISSUE TITLE
输出的sing-box配置文件在1.8.0正式版下无法连接

### ISSUE THREAD

**Issue by gbinhe** [fscarmen/sba#6]
sing-box 1.80正式版发布了，脚本输出的sing-box配置文件不能连接，输出的v2rayN链接可以正常使用。

**Comment by fscarmen2** [comment]
好的，我看看新的格式是如何的

**Comment by fscarmen** [comment]
好的，我看看新的格式是如何的，改下

**Comment by fscarmen** [comment]
我试了一下可以啊，脚本输出的只有节点方面的outbound，其他inbound, dns, rule-set 等都没有的，1.8.0的整体客户端配置文件改了，你要一并更新才行。

![image](https://github.com/fscarmen/sba/assets/62703343/c06781f8-2c00-4842-8b75-251cd1621746)

<img width="993" alt="image" src="https://github.com/fscarmen/sba/assets/62703343/86d9f0fc-5b52-49ca-9d42-e8fac0df65a6">

**Comment by gbinhe** [comment]
能否给个sing-box完整配置文件的示例？实在自己手搓不成功，麻烦了多谢！

**Comment by fscarmen** [comment]
#更新

修改客户端示例中的一部分路由规则，可能会解决一些udp协议节点无法连接的问题

https://t.me/ztvps/62
https://t.me/ztvps/64
https://t.me/ztvps/67

你安装好输出节点的时间，也有这个完整模板的提示的。

**Comment by gbinhe** [comment]
多谢，完整示例找到了，我在慢慢学习。另外Argo我用Token和固定域名安装的就 不通，用脚本临时域名安装的就可以，cloudflare主页显示隧道状态是正常的，这问题该怎么解决呢？
![Snipaste_2024-01-14_21-13-33](https://github.com/fscarmen/sba/assets/139198660/e1340011-ed0b-45a9-9663-ce32fe24c891)

**Comment by gbinhe** [comment]
错误信息是：+0800 2024-01-14 21:16:54 ERROR [4022014162 1.60s] inbound/http[http]: process connection from 127.0.0.1:11879: remote error: tls: handshake failure

**Comment by fscarmen** [comment]
我这里也是可以的，常用的要用固定的域名

**Comment by fscarmen** [comment]
你用其他客户端测测节点通不通，在看是节点问题还是客户端问题

**Comment by gbinhe** [comment]
我用sing-box和v2rayN都是测不通的，只有直连的vless-reality-vision节点通。手机端sing-box和Shadowrocket也不通。
错误信息如下：
+0800 2024-01-14 21:27:20 ERROR dns: exchange failed for mtalk.google.com. IN A: remote error: tls: handshake failure
+0800 2024-01-14 21:27:23 ERROR [604991654 584ms] inbound/tun[tun-in]: remote error: tls: handshake failure
+0800 2024-01-14 21:27:23 ERROR [771428370 600ms] inbound/tun[tun-in]: remote error: tls: handshake failure
+0800 2024-01-14 21:27:24 ERROR [3972712712 1.56s] inbound/tun[tun-in]: remote error: tls: handshake failure
+0800 2024-01-14 21:27:25 ERROR [2717109280 632ms] inbound/tun[tun-in]: remote error: tls: handshake failure
+0800 2024-01-14 21:27:26 ERROR dns: exchange failed for mtalk.google.com. IN A: remote error: tls: handshake failure
+0800 2024-01-14 21:27:26 ERROR dns: exchange failed for www.msftconnecttest.com. IN A: remote error: tls: handshake failure
+0800 2024-01-14 21:27:32 ERROR [4082765079 582ms] inbound/tun[tun-in]: remote error: tls: handshake failure

**Comment by fscarmen** [comment]
试下换优选域名

**Comment by gbinhe** [comment]
优选的前十个域名都试了，还是不行呢

**Comment by fscarmen** [comment]
又看了一下你的域名是cloudns.biz的，这个域名我看过介绍，挺复杂的，要两个网都做记录的。
现你用临时域名可以，说明客户端和vps没问题，那剩下域名这里了，试下换别的正常点的域名看看

**Comment by gbinhe** [comment]
两边都配置了CNAME记录了，我想不出哪里的问题了，临时域名可以我先用着临时域名吧，等我有别的域名的时候再换了试下，多谢！
