### ISSUE TITLE
AWS EC2 纯IPV6主机，Vmess不可用

### ISSUE THREAD

**Issue by meteorain** [fscarmen/sba#7]
首先提醒大家，CF的SSL设置要改为第三个：完全（端到端加密，使用服务器上的自签名证书），设置成“灵活”Vless连不通，设置成完全的话Vless可正常使用。但很奇怪ArgoX脚本反而需要CF SSL设置成“灵活”，这个我没时间去验证是否如此。

最新版本，默认配置，EC2 Ubuntu系统，几乎所有的协议都默认可用，除了Vmess，这个直连可以（需要手工更改客户端上的配置为直连），但通过 Cloudflare 绑定域名的方式就连不上，V2ray，Clash Meta，Nekobox几个客户端都试了不行。

另外还有一个客户端配置上的issue，Nekobox不支持（应该是sing-box不支持）ws path的“ed”参数，所以“?ed=2048”这个参数需要在脚本最后输出的配置清单中，在Nekobox部分中删除它。

**Comment by fscarmen** [comment]
> Nekobox不支持（应该是sing-box不支持）ws path的“ed”参数，所以“?ed=2048”这个参数需要在脚本最后输出的配置清单中，在Nekobox部分中删除它。

我这里3个ws协议，路径加了 ?ed=2048 都可以哦

<img width="1424" alt="image" src="https://github.com/fscarmen/sba/assets/62703343/5c1f9163-35ae-492f-87e2-34dd80aebc5c">
