### ISSUE TITLE
大佬，关于Argo-Nezha-Service-Container的问题。

### ISSUE THREAD

**Issue by 3377** [fscarmen/sba#8]
大佬，您好，由于Argo-Nezha-Service-Container没开issues，所以不得以在这请教下。
当前Argo-Nezha-Service-Container用的狠流畅，目前可能由于某些地方失效存在两个问题，还请方便的时候帮忙解答下。
1、GitHub私库不自动备份
2、无法自动更新面板数据
感谢。

**Comment by fscarmen** [comment]
https://github.com/fscarmen2/Argo-Nezha-Service-Container

来这里提，你手动运行 `bash -x /dashboard/backup.sh` 看看日志
