### ISSUE TITLE
Argo Tunnel 状态总是显示degraded

### ISSUE THREAD

**Issue by xiaosahuogui** [fscarmen/sba#9]
安装好之后Argo Tunnel 状态始终显示degraded，换了隧道也是一样显示degraded，节点倒是通，但是速度不太正常，会慢一点。

**Comment by fscarmen** [comment]
你安装了warp？

**Comment by xiaosahuogui** [comment]
是的，VPS的IP会被谷歌识别成国内IP， 只能套个Warp

**Comment by fscarmen** [comment]
无计，是黄色的了。不过挺奇怪的，我在 IPv6 only 的机器上安装了warp，再安装 sba，隧道是绿色的。

**Comment by xiaosahuogui** [comment]
是的，如果ipv6也套上warp就变黄色了。

**Comment by fscarmen** [comment]
我在 vc ipv6 only 的机器上安装了 warp，隧道是绿色的哦

**Comment by xiaosahuogui** [comment]
好奇怪，我在德鸡上套双栈ipv4+ipv6就变成黄色，只套ipv4就是绿色，只能先分流一下用着了。

**Comment by fscarmen** [comment]
不奇怪的，因为他是 IPv6 连着 argo 的，如果你 IPv6 是原生，就是绿色 ，如果是 warpV6，就是黄色，你试试换成 warp IPv6 only，不要 v4，一样是黄色的。
